services:
  app:
    #image: python:3.11
    build: .
    container_name: ecuelle_app
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      PROXY_PORT: ${PROXY_PORT}
      DB_TYPE: ${DB_TYPE}
    ports:
      - "8080:80"
      - "${PROXY_PORT}:${PROXY_PORT}"
    depends_on:
      - ${DB_TYPE}

  mysql:
    image: mysql:5.7
    profiles: ["mysql"]
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      default:
        aliases:
          - db

  postgres:
    image: postgres:14.22-alpine
    profiles: ["postgres"]
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: my-secret-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    profiles: ["mssql"]
    container_name: mssql_db
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Mys3cretPassword-123
    networks:
      default:
        aliases:
          - db

volumes:
  mysql_data:
  postgres_data:
  mssql_data:
