from enum import Enum

class Capability(Enum):
    CLIENT_LONG_PASSWORD = 1
    CLIENT_FOUND_ROWS = 2
    CLIENT_LONG_FLAG = 1 << 2
    CLIENT_CONNECT_WITH_DB = 1 << 3
    CLIENT_NO_SCHEMA =  1 << 4
    CLIENT_COMPRESS = 1 << 5
    CLIENT_ODBC = 1 << 6
    CLIENT_LOCAL_FILES = 1 << 7
    CLIENT_IGNORE_SPACE = 1 << 8
    CLIENT_PROTOCOL_41 = 1 << 9
    CLIENT_INTERACTIVE = 1 << 10
    CLIENT_SSL = 1 << 11
    CLIENT_IGNORE_SIGPIPE = 1 << 12
    CLIENT_TRANSACTIONS = 1 << 13
    CLIENT_RESERVED = 1 << 14
    CLIENT_RESERVED2 =  1 << 15
    CLIENT_MULTI_STATEMENTS = 1 << 16
    CLIENT_MULTI_RESULTS = 1 << 17
    CLIENT_PS_MULTI_RESULTS = 1 << 18
    CLIENT_PLUGIN_AUTH = 1 << 19
    CLIENT_CONNECT_ATTRS = 1 << 20
    CLIENT_PLUGIN_AUTH_LENENC_CLIENT_DATA = 1 << 21
    CLIENT_CAN_HANDLE_EXPIRED_PASSWORDS = 1 << 22
    CLIENT_SESSION_TRACK = 1 << 23
    CLIENT_DEPRECATE_EOF = 1 << 24
    CLIENT_OPTIONAL_RESULTSET_METADATA = 1 << 25
    CLIENT_ZSTD_COMPRESSION_ALGORITHM = 1 << 26
    CLIENT_QUERY_ATTRIBUTES = 1 << 27
    MULTI_FACTOR_AUTHENTICATION = 1 << 28
    CLIENT_CAPABILITY_EXTENSION = 1 << 29
    CLIENT_SSL_VERIFY_SERVER_CERT = 1 << 30
    CLIENT_REMEMBER_OPTIONS = 1 << 31

class FieldType(Enum):
    FIELD_TYPE_TINY = 1
    FIELD_TYPE_SHORT = 2
    FIELD_TYPE_LONG = 3
    FIELD_TYPE_FLOAT = 4
    FIELD_TYPE_DOUBLE = 5
    FIELD_TYPE_TIMESTAMP = 7
    FIELD_TYPE_LONGLONG = 8
    FIELD_TYPE_INT24 = 9
    FIELD_TYPE_DATE = 10
    FIELD_TYPE_TIME = 11
    FIELD_TYPE_DATETIME = 12
    FIELD_TYPE_YEAR = 13
    FIELD_TYPE_UNKNOWN = 245
    FIELD_TYPE_NEWDECIMAL = 246
    FIELD_TYPE_BLOB = 252
    FIELD_TYPE_VAR_STRING = 253
    FIELD_TYPE_STRING = 254


class PacketType(Enum):
    PACKET_OK = 1
    PACKET_EOF = 2
    PACKET_ERR = 3
    PACKET_HANDSHAKE = 4
    PACKET_HANDSHAKE_RESPONSE = 5
    PACKET_CACHING_SHA2 = 6
    PACKET_QUERY = 7
    PACKET_PREPARE_STATEMENT = 8
    PACKET_EXECUTE_STATEMENT = 9
    PACKET_TABULAR_RESPONSE = 10
    PACKET_CLOSE = 11
    PACKET_QUIT = 12
    PACKET_UNKNOWN = 99