CREATE TABLE example_types (
    id INT,
    big_number BIGINT,
    small_number SMALLINT,
    tiny_number TINYINT,
    decimal_value DECIMAL(10,2),
    float_value FLOAT,
    bit_value BIT,
    char_value CHAR(10),
    varchar_value VARCHAR(100),
    text_value TEXT,
    date_value DATE,
    time_value TIME,
    datetime_value DATETIME,
    datetime2_value DATETIME2,
    binary_value BINARY(4),
    varbinary_value VARBINARY(10),
    unique_id UNIQUEIDENTIFIER
);

INSERT INTO example_types (
    id,
    big_number,
    small_number,
    tiny_number,
    decimal_value,
    float_value,
    bit_value,
    char_value,
    varchar_value,
    text_value,
    date_value,
    time_value,
    datetime_value,
    datetime2_value,
    binary_value,
    varbinary_value,
    unique_id
) VALUES (
    1,
    9000000000,
    32000,
    200,
    12345.67,
    3.14159,
    1,
    'CHARVAL',
    'Example varchar',
    'Example long text',
    '2026-03-06',
    '14:30:00',
    '2026-03-06 14:30:00',
    '2026-03-06 14:30:00.123456',
    0x12345678,
    0xABCDEF,
    NEWID()
);